import type { Topic } from "./types";

export const topics: Topic[] = [
	{
		id: "mixed",
		subject: "math",
		name: "Mix",
		description: "Kolo naprieč celým piatackym učivom.",
		icon: "⚡",
	},
	{
		id: "numbers",
		subject: "math",
		name: "Prirodzené čísla",
		description: "Rozklad, číselná os, porovnávanie, zaokrúhľovanie a rímske čísla.",
		icon: "🔢",
	},
	{
		id: "decimals",
		subject: "math",
		name: "Desatinné čísla",
		description: "Peniaze, porovnávanie, zaokrúhľovanie, sčítanie a násobenie 10, 100, 1000.",
		icon: "🔟",
	},
	{
		id: "fractions",
		subject: "math",
		name: "Zlomky",
		description: "Časť celku, polovice, tretiny, štvrtiny a jednoduché porovnávanie.",
		icon: "🍕",
	},
	{
		id: "geometry",
		subject: "math",
		name: "Geometria",
		description: "Útvary, kružnica, kolmice, rovnobežky, telesá a stavby z kociek.",
		icon: "📐",
	},
	{
		id: "addition",
		subject: "math",
		name: "Sčítanie & odčítanie",
		description: "Spamäti, písomne, rozdielom, odhad a chýbajúce čísla.",
		icon: "➕",
	},
	{
		id: "symmetry",
		subject: "math",
		name: "Súmernosť",
		description: "Osová a stredová súmernosť, zrkadlenie a osi súmernosti.",
		icon: "◫",
	},
	{
		id: "multiplication",
		subject: "math",
		name: "Násobenie & delenie",
		description: "Viacciferné násobenie, delenie, zvyšok, zátvorky a násobky 10, 100, 1000.",
		icon: "✖️",
	},
	{
		id: "measurement",
		subject: "math",
		name: "Jednotky, obvod & obsah",
		description: "Premeny mm–km, obvody trojuholníka/štvorca/obdĺžnika a obsah v sieti.",
		icon: "📏",
	},
	{
		id: "applications",
		subject: "math",
		name: "Dáta & logika",
		description: "Slovné úlohy, peniaze, skutočné grafy, pravdepodobnosť a kombinatorika.",
		icon: "🧠",
	},
	{
		id: "sk-mixed",
		subject: "slovak",
		name: "Mix",
		description: "Pravopis, gramatika, čítanie, sloh aj literatúra v jednom kole.",
		icon: "⚡",
	},
	{
		id: "sk-spelling",
		subject: "slovak",
		name: "Pravopis",
		description: "Doplňovačky i/í/y/ý, vybrané slová, rytmické krátenie a spodobovanie.",
		icon: "✍️",
	},
	{
		id: "sk-nouns",
		subject: "slovak",
		name: "Podstatné & prídavné mená",
		description: "Rod, číslo, pád, životnosť, vzory a stupňovanie prídavných mien.",
		icon: "🧩",
	},
	{
		id: "sk-vocabulary",
		subject: "slovak",
		name: "Slovná zásoba",
		description: "Synonymá, antonymá, viacvýznamové slová, nárečia a ustálené spojenia.",
		icon: "💬",
	},
	{
		id: "sk-sentences",
		subject: "slovak",
		name: "Vety & slovosled",
		description: "Druhy viet, správny slovosled, interpunkcia a zrozumiteľná veta.",
		icon: "🧱",
	},
	{
		id: "sk-reading",
		subject: "slovak",
		name: "Čítanie & sloh",
		description: "Hlavná myšlienka, téma, rozprávanie s opisom, pracovný postup a interview.",
		icon: "📖",
	},
	{
		id: "sk-literature",
		subject: "slovak",
		name: "Literatúra",
		description: "Pieseň, legenda, povesť, rozprávač, personifikácia, epiteton, rytmus a refrén.",
		icon: "🎭",
	},
];
